spring:
  application:
    name: cv-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2124dc/props-configurations.git
          default-label: main
          searchPaths: config/chavdar-vishranti/properties
          clone-on-start: true
server:
  port: '8061'
  ssl:
    enabled: 'false'

eureka:
  client:
    serviceUrl:
      defaultZone: http://103.168.18.176:8060/eureka/
  instance:
    prefer-ip-address: 'true'

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG
