spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${user.dir}/config/
        bootstrap: 'false'
  profiles:
    active: native

server:
  port: '8061'
  ssl:
    enabled: 'false'

eureka:
  client:
    serviceUrl:
      defaultZone: http://103.168.18.176:8060/eureka/
  instance:
    prefer-ip-address: 'true'
