spring:
  application:
    name: cv-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2124dc/props-configurations.git
          default-label: main
          searchPaths: config/chavdar-vishranti/properties
          clone-on-start: true
server:
  ssl:
    enabled: 'false'

# logging:
#   level:
#     org.springframework.cloud.config.server: DEBUG
#     org.eclipse.jgit: DEBUG
