spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: file:///system/projects/java/chavdar_vishranti/config/
        bootstrap: 'false'
  profiles:
    active: native

server:
  port: '8061'
  ssl:
    enabled: 'false'

eureka:
  client:
    serviceUrl:
      defaultZone: http://103.168.18.176:8060/eureka/
  instance:
    prefer-ip-address: 'true'

logging:
  level:
    # Set specific classes to a higher level to hide logs
    org.springframework.boot.autoconfigure.condition.OnClassCondition: ERROR
    org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration: ERROR
    org.springframework.boot.autoconfigure.condition: ERROR
