spring:
  config:
    activate:
      on-profile: prod

server:
  port: '8061'
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://103.168.18.176:8060/eureka/
  instance:
    prefer-ip-address: 'true'