spring:
  config:
    activate:
      on-profile: dev

server:
  port: '8061'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/
  instance:
    prefer-ip-address: 'true'
